demo-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=person
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
  volumes:
    - ./src/main/resources/mysql_init:/docker-entrypoint-initdb.d
 
springboot-docker-demo:
  image: jiwhiz/spring-boot-docker-mysql
  links:
    - demo-mysql:mysql
  ports:
    - 8888:8080
